#!/usr/bin/env bash
YANG_DIR="$1"
NAME="$2"
NED_DIR="$3"
echo PATH=$NCS_DIR/bin:$PATH ncs-make-package --verbose --netconf-ned "$YANG_DIR" "$NAME" --dest "$NED_DIR" --no-java
PATH=$NCS_DIR/bin:$PATH ncs-make-package --verbose --netconf-ned "$YANG_DIR" "$NAME" --dest "$NED_DIR" --no-java
echo make clean fxs -C "$3/src" NCSC="$NCS_DIR/bin/ncsc --verbose"
make clean fxs -C "$3/src" NCSC="$NCS_DIR/bin/ncsc --verbose" && touch "$NED_DIR"
